project:
  type: website

website:
  title: "Timon Scheuer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
lang: de


